FROM php:8-fpm

RUN apt-get update && \
    apt-get install -y git unzip libzip-dev libpq-dev && \
    docker-php-ext-install pdo pdo_mysql zip && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www/html

RUN chown -R www-data:www-data /var/www/html && \
    a2enmod rewrite

WORKDIR /var/www/html

RUN composer install --no-interaction
